repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: [kissml/, tests/, --fix]
      - id: ruff-format
        args: [kissml/, tests/]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [kissml/, tests/]

  - repo: https://github.com/blu3r4y/ty-pre-commit
    rev: v0.0.8
    hooks:
      - id: ty
        args: [kissml/, tests/]